/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ceresdb.proto;

public final class Common {
    private Common() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface ResponseHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:storage.ResponseHeader)
                                            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>uint32 code = 1;</code>
         */
        int getCode();

        /**
         * <code>string error = 2;</code>
         */
        java.lang.String getError();

        /**
         * <code>string error = 2;</code>
         */
        com.google.protobuf.ByteString getErrorBytes();
    }

    /**
     * Protobuf type {@code storage.ResponseHeader}
     */
    public static final class ResponseHeader extends com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:storage.ResponseHeader)
                                                                                           ResponseHeaderOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use ResponseHeader.newBuilder() to construct.
        private ResponseHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ResponseHeader() {
            code_ = 0;
            error_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private ResponseHeader(com.google.protobuf.CodedInputStream input,
                               com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                           throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                .newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            code_ = input.readUInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            error_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.ceresdb.proto.Common.internal_static_storage_ResponseHeader_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.ceresdb.proto.Common.internal_static_storage_ResponseHeader_fieldAccessorTable
                .ensureFieldAccessorsInitialized(com.ceresdb.proto.Common.ResponseHeader.class,
                    com.ceresdb.proto.Common.ResponseHeader.Builder.class);
        }

        public static final int CODE_FIELD_NUMBER = 1;
        private int             code_;

        /**
         * <code>uint32 code = 1;</code>
         */
        public int getCode() {
            return code_;
        }

        public static final int           ERROR_FIELD_NUMBER = 2;
        private volatile java.lang.Object error_;

        /**
         * <code>string error = 2;</code>
         */
        public java.lang.String getError() {
            java.lang.Object ref = error_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                error_ = s;
                return s;
            }
        }

        /**
         * <code>string error = 2;</code>
         */
        public com.google.protobuf.ByteString getErrorBytes() {
            java.lang.Object ref = error_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                error_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (code_ != 0) {
                output.writeUInt32(1, code_);
            }
            if (!getErrorBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, error_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (code_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeUInt32Size(1, code_);
            }
            if (!getErrorBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, error_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.ceresdb.proto.Common.ResponseHeader)) {
                return super.equals(obj);
            }
            com.ceresdb.proto.Common.ResponseHeader other = (com.ceresdb.proto.Common.ResponseHeader) obj;

            boolean result = true;
            result = result && (getCode() == other.getCode());
            result = result && getError().equals(other.getError());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CODE_FIELD_NUMBER;
            hash = (53 * hash) + getCode();
            hash = (37 * hash) + ERROR_FIELD_NUMBER;
            hash = (53 * hash) + getError().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.ceresdb.proto.Common.ResponseHeader parseFrom(java.nio.ByteBuffer data)
                                                                                                 throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.ceresdb.proto.Common.ResponseHeader parseFrom(java.nio.ByteBuffer data,
                                                                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                    throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.ceresdb.proto.Common.ResponseHeader parseFrom(com.google.protobuf.ByteString data)
                                                                                                            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.ceresdb.proto.Common.ResponseHeader parseFrom(com.google.protobuf.ByteString data,
                                                                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                    throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.ceresdb.proto.Common.ResponseHeader parseFrom(byte[] data)
                                                                                    throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.ceresdb.proto.Common.ResponseHeader parseFrom(byte[] data,
                                                                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                    throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.ceresdb.proto.Common.ResponseHeader parseFrom(java.io.InputStream input)
                                                                                                  throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.ceresdb.proto.Common.ResponseHeader parseFrom(java.io.InputStream input,
                                                                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                    throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.ceresdb.proto.Common.ResponseHeader parseDelimitedFrom(java.io.InputStream input)
                                                                                                           throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static com.ceresdb.proto.Common.ResponseHeader parseDelimitedFrom(java.io.InputStream input,
                                                                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                             throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                extensionRegistry);
        }

        public static com.ceresdb.proto.Common.ResponseHeader parseFrom(com.google.protobuf.CodedInputStream input)
                                                                                                                   throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.ceresdb.proto.Common.ResponseHeader parseFrom(com.google.protobuf.CodedInputStream input,
                                                                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                    throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.ceresdb.proto.Common.ResponseHeader prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code storage.ResponseHeader}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
                                                                                                         implements
                                                                                                         // @@protoc_insertion_point(builder_implements:storage.ResponseHeader)
                                                                                                         com.ceresdb.proto.Common.ResponseHeaderOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.ceresdb.proto.Common.internal_static_storage_ResponseHeader_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.ceresdb.proto.Common.internal_static_storage_ResponseHeader_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.ceresdb.proto.Common.ResponseHeader.class,
                        com.ceresdb.proto.Common.ResponseHeader.Builder.class);
            }

            // Construct using com.ceresdb.proto.Common.ResponseHeader.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                code_ = 0;

                error_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.ceresdb.proto.Common.internal_static_storage_ResponseHeader_descriptor;
            }

            public com.ceresdb.proto.Common.ResponseHeader getDefaultInstanceForType() {
                return com.ceresdb.proto.Common.ResponseHeader.getDefaultInstance();
            }

            public com.ceresdb.proto.Common.ResponseHeader build() {
                com.ceresdb.proto.Common.ResponseHeader result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.ceresdb.proto.Common.ResponseHeader buildPartial() {
                com.ceresdb.proto.Common.ResponseHeader result = new com.ceresdb.proto.Common.ResponseHeader(this);
                result.code_ = code_;
                result.error_ = error_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                                            java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                            java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.ceresdb.proto.Common.ResponseHeader) {
                    return mergeFrom((com.ceresdb.proto.Common.ResponseHeader) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.ceresdb.proto.Common.ResponseHeader other) {
                if (other == com.ceresdb.proto.Common.ResponseHeader.getDefaultInstance())
                    return this;
                if (other.getCode() != 0) {
                    setCode(other.getCode());
                }
                if (!other.getError().isEmpty()) {
                    error_ = other.error_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                 throws java.io.IOException {
                com.ceresdb.proto.Common.ResponseHeader parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.ceresdb.proto.Common.ResponseHeader) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int code_;

            /**
             * <code>uint32 code = 1;</code>
             */
            public int getCode() {
                return code_;
            }

            /**
             * <code>uint32 code = 1;</code>
             */
            public Builder setCode(int value) {

                code_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint32 code = 1;</code>
             */
            public Builder clearCode() {

                code_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object error_ = "";

            /**
             * <code>string error = 2;</code>
             */
            public java.lang.String getError() {
                java.lang.Object ref = error_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    error_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string error = 2;</code>
             */
            public com.google.protobuf.ByteString getErrorBytes() {
                java.lang.Object ref = error_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                        .copyFromUtf8((java.lang.String) ref);
                    error_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string error = 2;</code>
             */
            public Builder setError(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                error_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string error = 2;</code>
             */
            public Builder clearError() {

                error_ = getDefaultInstance().getError();
                onChanged();
                return this;
            }

            /**
             * <code>string error = 2;</code>
             */
            public Builder setErrorBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                error_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:storage.ResponseHeader)
        }

        // @@protoc_insertion_point(class_scope:storage.ResponseHeader)
        private static final com.ceresdb.proto.Common.ResponseHeader DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.ceresdb.proto.Common.ResponseHeader();
        }

        public static com.ceresdb.proto.Common.ResponseHeader getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ResponseHeader> PARSER = new com.google.protobuf.AbstractParser<ResponseHeader>() {
                                                                                   public ResponseHeader parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                                                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                                      throws com.google.protobuf.InvalidProtocolBufferException {
                                                                                       return new ResponseHeader(input,
                                                                                           extensionRegistry);
                                                                                   }
                                                                               };

        public static com.google.protobuf.Parser<ResponseHeader> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ResponseHeader> getParserForType() {
            return PARSER;
        }

        public com.ceresdb.proto.Common.ResponseHeader getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor                internal_static_storage_ResponseHeader_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_storage_ResponseHeader_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\014common.proto\022\007storage\"-\n\016ResponseHeade"
                                              + "r\022\014\n\004code\030\001 \001(\r\022\r\n\005error\030\002 \001(\tB\033\n\021com.ce"
                                              + "resdb.protoB\006Commonb\006proto3" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
        internal_static_storage_ResponseHeader_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_storage_ResponseHeader_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_storage_ResponseHeader_descriptor, new java.lang.String[] { "Code", "Error", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
